spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  application:
    name: resume builder
    templates:
      ppt-templates-classpath: templates/ppt/
      ppt-output-path: output/ppt/
      pdf-templates-classpath: /
      pdf-output-path: output/pdf/
      images-classpath: images/
    openai-api:
      key:
      url: https://api.openai.com/v1/chat/completions
      model: gpt-3.5-turbo-1106